using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


public class Skills
{
    public static Skill FromID(int id)
    {
        return list[id];
    }

    public static Skill SkillFromRoleID(Role role, int skillId)
    {
        Skill skill = list.FirstOrDefault(it => it.role == role && it.skillId == skillId);
        if(skill == null) { skill = list[0]; } //Set to None as default
        return skill;
    }

    public static readonly List<Skill> list = new List<Skill>
    {
        new Skill(0){collection=0, role=Role.NONE, skillCost=0, dataName="None", originalName="None", skillId=0},
        new Skill(1){collection=6, role=Role.BEAST_FRIEND, skillCost=0, dataName="Chittering Mouse", originalName="Chittering Mouse", skillId=1},
        new Skill(2){collection=6, role=Role.BEAST_FRIEND, skillCost=0, dataName="Nightingale", originalName="Nightingale", skillId=2},
        new Skill(3){collection=6, role=Role.BEAST_FRIEND, skillCost=6, dataName="Pet Rabbit", originalName="Pet Rabbit", skillId=3},
        new Skill(4){collection=6, role=Role.BEAST_FRIEND, skillCost=6, dataName="Band of Squirrels", originalName="Band of Squirrels", skillId=4},
        new Skill(5){collection=6, role=Role.BEAST_FRIEND, skillCost=8, dataName="Iron Hills Goat", originalName="Iron Hills Goat", skillId=5},
        new Skill(6){collection=6, role=Role.BEAST_FRIEND, skillCost=8, dataName="Lómë", originalName="Lómë", skillId=6},

        new Skill(7){collection=1, role=Role.BURGLAR, skillCost=0, dataName="Self-Sufficient", originalName="Self-Sufficient", skillId=1},
        new Skill(8){collection=1, role=Role.BURGLAR, skillCost=0, dataName="Quiet", originalName="Quiet", skillId=2},
        new Skill(9){collection=1, role=Role.BURGLAR, skillCost=0, dataName="Quiet", originalName="Quiet", skillId=3},
        new Skill(10){collection=1, role=Role.BURGLAR, skillCost=3, dataName="Word of Fortune", originalName="Word of Fortune", skillId=4},
        new Skill(11){collection=1, role=Role.BURGLAR, skillCost=3, dataName="Sneaking", originalName="Sneaking", skillId=5},
        new Skill(12){collection=1, role=Role.BURGLAR, skillCost=3, dataName="Pockets", originalName="Pockets", skillId=6},
        new Skill(13){collection=1, role=Role.BURGLAR, skillCost=7, dataName="What Is In my Pocket?", originalName="What Is In my Pocket?", skillId=7},
        new Skill(14){collection=1, role=Role.BURGLAR, skillCost=7, dataName="Self-Sufficient", originalName="Self-Sufficient", skillId=8},
        new Skill(15){collection=1, role=Role.BURGLAR, skillCost=7, dataName="Hidden Blades", originalName="Hidden Blades", skillId=9},
        new Skill(16){collection=1, role=Role.BURGLAR, skillCost=7, dataName="Unseen Strike", originalName="Unseen Strike", skillId=10},
        new Skill(17){collection=1, role=Role.BURGLAR, skillCost=12, dataName="Quick Thinking", originalName="Quick Thinking", skillId=11},
        new Skill(18){collection=1, role=Role.BURGLAR, skillCost=12, dataName="Embrace the Darkness", originalName="Embrace the Darkness", skillId=12},

        new Skill(19){collection=1, role=Role.CAPTAIN, skillCost=0, dataName="Well Provisioned", originalName="Well Provisioned", skillId=1},
        new Skill(20){collection=1, role=Role.CAPTAIN, skillCost=0, dataName="Lead the Charge", originalName="Lead the Charge", skillId=2},
        new Skill(21){collection=1, role=Role.CAPTAIN, skillCost=0, dataName="Lead the Charge", originalName="Lead the Charge", skillId=3},
        new Skill(22){collection=1, role=Role.CAPTAIN, skillCost=3, dataName="Word of Triumph", originalName="Word of Triumph", skillId=4},
        new Skill(23){collection=1, role=Role.CAPTAIN, skillCost=3, dataName="Stand Together", originalName="Stand Together", skillId=5},
        new Skill(24){collection=1, role=Role.CAPTAIN, skillCost=3, dataName="A Fey Mood", originalName="A Fey Mood", skillId=6},
        new Skill(25){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="Empowering Words", originalName="Empowering Words", skillId=7},
        new Skill(26){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="Inspiring Presence", originalName="Inspiring Presence", skillId=8},
        new Skill(27){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="To Me!", originalName="To Me!", skillId=9},
        new Skill(28){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="Battle Plan", originalName="Battle Plan", skillId=10},
        new Skill(29){collection=1, role=Role.CAPTAIN, skillCost=12, dataName="A Wind Among Grass", originalName="A Wind Among Grass", skillId=11},
        new Skill(30){collection=1, role=Role.CAPTAIN, skillCost=12, dataName="Master Tactician", originalName="Master Tactician", skillId=12},

        new Skill(31){collection=3, role=Role.DELVER, skillCost=0, dataName="Intrepid", originalName="Intrepid", skillId=1},
        new Skill(32){collection=3, role=Role.DELVER, skillCost=0, dataName="Shadow Sight", originalName="Shadow Sight", skillId=2},
        new Skill(33){collection=3, role=Role.DELVER, skillCost=0, dataName="Shadow Sight", originalName="Shadow Sight", skillId=3},
        new Skill(34){collection=3, role=Role.DELVER, skillCost=3, dataName="Wiles", originalName="Wiles", skillId=4},
        new Skill(35){collection=3, role=Role.DELVER, skillCost=3, dataName="Crushing Blow", originalName="Crushing Blow", skillId=5},
        new Skill(36){collection=3, role=Role.DELVER, skillCost=3, dataName="Boasting", originalName="Boasting", skillId=6},
        new Skill(37){collection=3, role=Role.DELVER, skillCost=7, dataName="Forging Ahead", originalName="Forging Ahead", skillId=7},
        new Skill(38){collection=3, role=Role.DELVER, skillCost=7, dataName="Spirit of Adventure", originalName="Spirit of Adventure", skillId=8},
        new Skill(39){collection=3, role=Role.DELVER, skillCost=7, dataName="No Stone Unturned", originalName="No Stone Unturned", skillId=9},
        new Skill(40){collection=3, role=Role.DELVER, skillCost=7, dataName="No Stone Unturned", originalName="No Stone Unturned", skillId=10},
        new Skill(41){collection=3, role=Role.DELVER, skillCost=12, dataName="Glory", originalName="Glory", skillId=11},
        new Skill(42){collection=3, role=Role.DELVER, skillCost=12, dataName="Treasures Untold", originalName="Treasures Untold", skillId=12},

        new Skill(43){collection=1, role=Role.GUARDIAN, skillCost=0, dataName="You Cannot Pass", originalName="You Cannot Pass", skillId=1},
        new Skill(44){collection=1, role=Role.GUARDIAN, skillCost=0, dataName="Ready Defense", originalName="Ready Defense", skillId=2},
        new Skill(45){collection=1, role=Role.GUARDIAN, skillCost=0, dataName="Ready Defense", originalName="Ready Defense", skillId=3},
        new Skill(46){collection=1, role=Role.GUARDIAN, skillCost=3, dataName="Word of Glory", originalName="Word of Glory", skillId=4},
        new Skill(47){collection=1, role=Role.GUARDIAN, skillCost=3, dataName="Noble Sacrifice", originalName="Noble Sacrifice", skillId=5},
        new Skill(48){collection=1, role=Role.GUARDIAN, skillCost=3, dataName="Desperate Defense", originalName="Desperate Defense", skillId=6},
        new Skill(49){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Voice Like Ringing Steel", originalName="Voice Like Ringing Steel", skillId=7},
        new Skill(50){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Ready Defense", originalName="Ready Defense", skillId=8},
        new Skill(51){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Guarded Strike", originalName="Guarded Strike", skillId=9},
        new Skill(52){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Grim Resolve", originalName="Grim Resolve", skillId=10},
        new Skill(53){collection=1, role=Role.GUARDIAN, skillCost=12, dataName="Final Defense", originalName="Final Defense", skillId=11},
        new Skill(54){collection=1, role=Role.GUARDIAN, skillCost=12, dataName="Defense Instruction", originalName="Defense Instruction", skillId=12},

        new Skill(55){collection=5, role=Role.GUIDE, skillCost=0, dataName="Great Hound", originalName="Great Hound", skillId=1},
        new Skill(56){collection=5, role=Role.GUIDE, skillCost=0, dataName="The Way Forward", originalName="The Way Forward", skillId=2},
        new Skill(57){collection=5, role=Role.GUIDE, skillCost=0, dataName="The Way Forward", originalName="The Way Forward", skillId=3},
        new Skill(58){collection=5, role=Role.GUIDE, skillCost=3, dataName="Helping Hand", originalName="Helping Hand", skillId=4},
        new Skill(59){collection=5, role=Role.GUIDE, skillCost=3, dataName="Point the Way", originalName="Point the Way", skillId=5},
        new Skill(60){collection=5, role=Role.GUIDE, skillCost=3, dataName="Lead by Example", originalName="Lead by Example", skillId=6},
        new Skill(61){collection=5, role=Role.GUIDE, skillCost=7, dataName="Alert", originalName="Alert", skillId=7},
        new Skill(62){collection=5, role=Role.GUIDE, skillCost=7, dataName="Ancient Trails", originalName="Ancient Trails", skillId=8},
        new Skill(63){collection=5, role=Role.GUIDE, skillCost=7, dataName="Teamwork", originalName="Teamwork", skillId=9},
        new Skill(64){collection=5, role=Role.GUIDE, skillCost=7, dataName="Survival Training", originalName="Survival Training", skillId=10},
        new Skill(65){collection=5, role=Role.GUIDE, skillCost=12, dataName="All Together", originalName="All Together", skillId=11},
        new Skill(66){collection=5, role=Role.GUIDE, skillCost=12, dataName="Timely Assistance", originalName="Timely Assistance", skillId=12},

        new Skill(67){collection=3, role=Role.HERBALIST, skillCost=0, dataName="Curiosity", originalName="Curiosity", skillId=1},
        new Skill(68){collection=3, role=Role.HERBALIST, skillCost=0, dataName="Gathered Wisdom", originalName="Gathered Wisdom", skillId=2},
        new Skill(69){collection=3, role=Role.HERBALIST, skillCost=0, dataName="Gathered Wisdom", originalName="Gathered Wisdom", skillId=3},
        new Skill(70){collection=3, role=Role.HERBALIST, skillCost=3, dataName="Study of Nature", originalName="Study of Nature", skillId=4},
        new Skill(71){collection=3, role=Role.HERBALIST, skillCost=3, dataName="Hands of a Healer", originalName="Hands of a Healer", skillId=5},
        new Skill(72){collection=3, role=Role.HERBALIST, skillCost=3, dataName="Insight", originalName="Insight", skillId=6},
        new Skill(73){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Calming Presence", originalName="Calming Presence", skillId=7},
        new Skill(74){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Athelas", originalName="Athelas", skillId=8},
        new Skill(75){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Natural Remedy", originalName="Natural Remedy", skillId=9},
        new Skill(76){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Innovation", originalName="Innovation", skillId=10},
        new Skill(77){collection=3, role=Role.HERBALIST, skillCost=12, dataName="Phosphorescence", originalName="Phosphorescence", skillId=11},
        new Skill(78){collection=3, role=Role.HERBALIST, skillCost=12, dataName="Healing Poultice", originalName="Healing Poultice", skillId=12},

        new Skill(79){collection=1, role=Role.HUNTER, skillCost=0, dataName="Resourceful", originalName="Resourceful", skillId=1},
        new Skill(80){collection=1, role=Role.HUNTER, skillCost=0, dataName="Precise Strike", originalName="Precise Strike", skillId=2},
        new Skill(81){collection=1, role=Role.HUNTER, skillCost=0, dataName="Precise Strike", originalName="Precise Strike", skillId=3},
        new Skill(82){collection=1, role=Role.HUNTER, skillCost=3, dataName="Resourceful", originalName="Resourceful", skillId=4},
        new Skill(83){collection=1, role=Role.HUNTER, skillCost=3, dataName="Coordinated Strike", originalName="Coordinated Strike", skillId=5},
        new Skill(84){collection=1, role=Role.HUNTER, skillCost=3, dataName="Quick Snare", originalName="Quick Snare", skillId=6},
        new Skill(85){collection=1, role=Role.HUNTER, skillCost=7, dataName="Death Stroke", originalName="Death Stroke", skillId=7},
        new Skill(86){collection=1, role=Role.HUNTER, skillCost=7, dataName="Barrage", originalName="Barrage", skillId=8},
        new Skill(87){collection=1, role=Role.HUNTER, skillCost=7, dataName="Falcon Companion", originalName="Falcon Companion", skillId=9},
        new Skill(88){collection=1, role=Role.HUNTER, skillCost=7, dataName="Gather Supplies", originalName="Gather Supplies", skillId=10},
        new Skill(89){collection=1, role=Role.HUNTER, skillCost=12, dataName="On the Hunt", originalName="On the Hunt", skillId=11},
        new Skill(90){collection=1, role=Role.HUNTER, skillCost=12, dataName="Stalk Prey", originalName="Stalk Prey", skillId=12},

        new Skill(91){collection=5, role=Role.LOREKEEPER, skillCost=0, dataName="Preparation", originalName="Preparation", skillId=1},
        new Skill(92){collection=5, role=Role.LOREKEEPER, skillCost=0, dataName="Childhood Tales", originalName="Childhood Tales", skillId=2},
        new Skill(93){collection=5, role=Role.LOREKEEPER, skillCost=0, dataName="Childhood Tales", originalName="Childhood Tales", skillId=3},
        new Skill(94){collection=5, role=Role.LOREKEEPER, skillCost=3, dataName="Driven by Knowedge", originalName="Driven by Knowedge", skillId=4},
        new Skill(95){collection=5, role=Role.LOREKEEPER, skillCost=3, dataName="Wisdom beyond Years", originalName="Wisdom beyond Years", skillId=5},
        new Skill(96){collection=5, role=Role.LOREKEEPER, skillCost=3, dataName="Wit beyond Measure", originalName="Wit beyond Measure", skillId=6},
        new Skill(97){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Ancestry", originalName="Ancestry", skillId=7},
        new Skill(98){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Collector", originalName="Collector", skillId=8},
        new Skill(99){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Secrets of the Wide World", originalName="Secrets of the Wide World", skillId=9},
        new Skill(100){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Song of History", originalName="Song of History", skillId=10},
        new Skill(101){collection=5, role=Role.LOREKEEPER, skillCost=12, dataName="Keeper of the Chronicle", originalName="Keeper of the Chronicle", skillId=11},
        new Skill(102){collection=5, role=Role.LOREKEEPER, skillCost=12, dataName="Exploit Weakness", originalName="Exploit Weakness", skillId=12},

        new Skill(103){collection=3, role=Role.MEDDLER, skillCost=0, dataName="Nosy", originalName="Nosy", skillId=1},
        new Skill(104){collection=3, role=Role.MEDDLER, skillCost=0, dataName="Guidance", originalName="Guidance", skillId=2},
        new Skill(105){collection=3, role=Role.MEDDLER, skillCost=0, dataName="Guidance", originalName="Guidance", skillId=3},
        new Skill(106){collection=3, role=Role.MEDDLER, skillCost=3, dataName="Gossip", originalName="Gossip", skillId=4},
        new Skill(107){collection=3, role=Role.MEDDLER, skillCost=3, dataName="Fast Talking", originalName="Fast Talking", skillId=5},
        new Skill(108){collection=3, role=Role.MEDDLER, skillCost=7, dataName="Interfering", originalName="Interfering", skillId=6},
        new Skill(109){collection=3, role=Role.MEDDLER, skillCost=7, dataName="Ancient Legend", originalName="Ancient Legend", skillId=7},
        new Skill(110){collection=3, role=Role.MEDDLER, skillCost=12, dataName="Contemplation", originalName="Contemplation", skillId=8},
        new Skill(111){collection=3, role=Role.MEDDLER, skillCost=12, dataName="Flattery", originalName="Flattery", skillId=9},
        new Skill(112){collection=3, role=Role.MEDDLER, skillCost=12, dataName="Hidden Plans", originalName="Hidden Plans", skillId=10},
        new Skill(113){collection=3, role=Role.MEDDLER, skillCost=16, dataName="Quick Temper", originalName="Quick Temper", skillId=11},
        new Skill(114){collection=3, role=Role.MEDDLER, skillCost=16, dataName="Strong Opinions", originalName="Strong Opinions", skillId=12},

        new Skill(115){collection=1, role=Role.MUSICIAN, skillCost=0, dataName="Endless Melody", originalName="Endless Melody", skillId=1},
        new Skill(116){collection=1, role=Role.MUSICIAN, skillCost=0, dataName="Travelling Song", originalName="Travelling Song", skillId=2},
        new Skill(117){collection=1, role=Role.MUSICIAN, skillCost=0, dataName="Travelling Song", originalName="Travelling Song", skillId=3},
        new Skill(118){collection=1, role=Role.MUSICIAN, skillCost=3, dataName="Word of Peace", originalName="Word of Peace", skillId=4},
        new Skill(119){collection=1, role=Role.MUSICIAN, skillCost=3, dataName="Song of Mocking", originalName="Song of Mocking", skillId=5},
        new Skill(120){collection=1, role=Role.MUSICIAN, skillCost=3, dataName="A Bit of Nonsense", originalName="A Bit of Nonsense", skillId=6},
        new Skill(121){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Endless Wonder", originalName="Endless Wonder", skillId=7},
        new Skill(122){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Durin's Song", originalName="Durin's Song", skillId=8},
        new Skill(123){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Lay of Nimrodel", originalName="Lay of Nimrodel", skillId=9},
        new Skill(124){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Burst Into Song", originalName="Burst Into Song", skillId=10},
        new Skill(125){collection=1, role=Role.MUSICIAN, skillCost=12, dataName="Crescendo of Dawn", originalName="Crescendo of Dawn", skillId=11},
        new Skill(126){collection=1, role=Role.MUSICIAN, skillCost=12, dataName="Tale of Tinuviel", originalName="Tale of Tinuviel", skillId=12},

        new Skill(127){collection=1, role=Role.PATHFINDER, skillCost=0, dataName="Trailblazer", originalName="Trailblazer", skillId=1},
        new Skill(128){collection=1, role=Role.PATHFINDER, skillCost=0, dataName="Paths Unseen", originalName="Paths Unseen", skillId=2},
        new Skill(129){collection=1, role=Role.PATHFINDER, skillCost=0, dataName="Paths Unseen", originalName="Paths Unseen", skillId=3},
        new Skill(130){collection=1, role=Role.PATHFINDER, skillCost=3, dataName="Word of Warning", originalName="Word of Warning", skillId=4},
        new Skill(131){collection=1, role=Role.PATHFINDER, skillCost=3, dataName="Baited Trap", originalName="Baited Trap", skillId=5},
        new Skill(132){collection=1, role=Role.PATHFINDER, skillCost=3, dataName="Trail Sign", originalName="Trail Sign", skillId=6},
        new Skill(133){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="Ambush", originalName="Ambush", skillId=7},
        new Skill(134){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="Ambush", originalName="Ambush", skillId=8},
        new Skill(135){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="A Shortcut", originalName="A Shortcut", skillId=9},
        new Skill(136){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="Find a Way", originalName="Find a Way", skillId=10},
        new Skill(137){collection=1, role=Role.PATHFINDER, skillCost=12, dataName="Unstoppable", originalName="Unstoppable", skillId=11},
        new Skill(138){collection=1, role=Role.PATHFINDER, skillCost=12, dataName="Honed Instinct", originalName="Honed Instinct", skillId=12},

        new Skill(139){collection=5, role=Role.PROVISIONER, skillCost=0, dataName="Foraging", originalName="Foraging", skillId=1},
        new Skill(140){collection=5, role=Role.PROVISIONER, skillCost=0, dataName="Waybread", originalName="Waybread", skillId=2},
        new Skill(141){collection=5, role=Role.PROVISIONER, skillCost=0, dataName="Waybread", originalName="Waybread", skillId=3},
        new Skill(142){collection=5, role=Role.PROVISIONER, skillCost=3, dataName="Mending", originalName="Mending", skillId=4},
        new Skill(143){collection=5, role=Role.PROVISIONER, skillCost=3, dataName="Gathering", originalName="Gathering", skillId=5},
        new Skill(144){collection=5, role=Role.PROVISIONER, skillCost=3, dataName="Good Cheer", originalName="Good Cheer", skillId=6},
        new Skill(145){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Herbs", originalName="Herbs", skillId=7},
        new Skill(146){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Respite", originalName="Respite", skillId=8},
        new Skill(147){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Pleasant Company", originalName="Pleasant Company", skillId=9},
        new Skill(148){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Heavy Packs", originalName="Heavy Packs", skillId=10},
        new Skill(149){collection=5, role=Role.PROVISIONER, skillCost=12, dataName="Feasting", originalName="Feasting", skillId=11},
        new Skill(150){collection=5, role=Role.PROVISIONER, skillCost=12, dataName="Hope Renewed", originalName="Hope Renewed", skillId=12},

        new Skill(151){collection=5, role=Role.SHIELDMAIDEN, skillCost=0, dataName="As One", originalName="As One", skillId=1},
        new Skill(152){collection=5, role=Role.SHIELDMAIDEN, skillCost=0, dataName="Call to Glory", originalName="Call to Glory", skillId=2},
        new Skill(153){collection=5, role=Role.SHIELDMAIDEN, skillCost=0, dataName="Call to Glory", originalName="Call to Glory", skillId=3},
        new Skill(154){collection=5, role=Role.SHIELDMAIDEN, skillCost=3, dataName="Taunting Cry", originalName="Taunting Cry", skillId=4},
        new Skill(155){collection=5, role=Role.SHIELDMAIDEN, skillCost=3, dataName="As One", originalName="As One", skillId=5},
        new Skill(156){collection=5, role=Role.SHIELDMAIDEN, skillCost=3, dataName="Press the Advantage", originalName="Press the Advantage", skillId=6},
        new Skill(157){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Back to Back", originalName="Back to Back", skillId=7},
        new Skill(158){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Momentum", originalName="Momentum", skillId=8},
        new Skill(159){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Force Them Back", originalName="Force Them Back", skillId=9},
        new Skill(160){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Flanking Strike", originalName="Flanking Strike", skillId=10},
        new Skill(161){collection=5, role=Role.SHIELDMAIDEN, skillCost=12, dataName="Overrun", originalName="Overrun", skillId=11},
        new Skill(162){collection=5, role=Role.SHIELDMAIDEN, skillCost=12, dataName="Carry the Day", originalName="Carry the Day", skillId=12},

        new Skill(163){collection=3, role=Role.SMITH, skillCost=0, dataName="Reforging", originalName="Reforging", skillId=1},
        new Skill(164){collection=3, role=Role.SMITH, skillCost=0, dataName="Thrice-Forged Steel", originalName="Thrice-Forged Steel", skillId=2},
        new Skill(165){collection=3, role=Role.SMITH, skillCost=0, dataName="Thrice-Forged Steel", originalName="Thrice-Forged Steel", skillId=3},
        new Skill(166){collection=3, role=Role.SMITH, skillCost=3, dataName="Unbowed", originalName="Unbowed", skillId=4},
        new Skill(167){collection=3, role=Role.SMITH, skillCost=3, dataName="Industrious", originalName="Industrious", skillId=5},
        new Skill(168){collection=3, role=Role.SMITH, skillCost=3, dataName="Industrious", originalName="Industrious", skillId=6},
        new Skill(169){collection=3, role=Role.SMITH, skillCost=7, dataName="Strike the Anvil", originalName="Strike the Anvil", skillId=7},
        new Skill(170){collection=3, role=Role.SMITH, skillCost=7, dataName="Dwarf-Linked Rings", originalName="Dwarf-Linked Rings", skillId=8},
        new Skill(171){collection=3, role=Role.SMITH, skillCost=7, dataName="Elf-Wrights' Grace", originalName="Elf-Wrights' Grace", skillId=9},
        new Skill(172){collection=3, role=Role.SMITH, skillCost=7, dataName="Craft of Men", originalName="Craft of Men", skillId=10},
        new Skill(173){collection=3, role=Role.SMITH, skillCost=12, dataName="Cirth Inscription", originalName="Cirth Inscription", skillId=11},
        new Skill(174){collection=3, role=Role.SMITH, skillCost=12, dataName="Forge's Fire", originalName="Forge's Fire", skillId=12},

        new Skill(175){collection=5, role=Role.SOLDIER, skillCost=0, dataName="Comrade in Arms", originalName="Comrade in Arms", skillId=1},
        new Skill(176){collection=5, role=Role.SOLDIER, skillCost=0, dataName="Love of War and Valour", originalName="Love of War and Valour", skillId=2},
        new Skill(177){collection=5, role=Role.SOLDIER, skillCost=0, dataName="Love of War and Valour", originalName="Love of War and Valour", skillId=3},
        new Skill(178){collection=5, role=Role.SOLDIER, skillCost=3, dataName="Fighting Advance", originalName="Fighting Advance", skillId=4},
        new Skill(179){collection=5, role=Role.SOLDIER, skillCost=3, dataName="Fighting Advance", originalName="Fighting Advance", skillId=5},
        new Skill(180){collection=5, role=Role.SOLDIER, skillCost=3, dataName="Fighting Advance", originalName="Fighting Advance", skillId=6},
        new Skill(181){collection=5, role=Role.SOLDIER, skillCost=7, dataName="On Your Orders", originalName="On Your Orders", skillId=7},
        new Skill(182){collection=5, role=Role.SOLDIER, skillCost=7, dataName="On Your Orders", originalName="On Your Orders", skillId=8},
        new Skill(183){collection=5, role=Role.SOLDIER, skillCost=7, dataName="Sleep Anywhere", originalName="Sleep Anywhere", skillId=9},
        new Skill(184){collection=5, role=Role.SOLDIER, skillCost=7, dataName="Sleep Anywhere", originalName="Sleep Anywhere", skillId=10},
        new Skill(185){collection=5, role=Role.SOLDIER, skillCost=12, dataName="Break the Wave", originalName="Break the Wave", skillId=11},
        new Skill(186){collection=5, role=Role.SOLDIER, skillCost=12, dataName="Break the Wave", originalName="Break the Wave", skillId=12},

        new Skill(187){collection=3, role=Role.TRAVELLER, skillCost=0, dataName="Over Ridge and Rill", originalName="Over Ridge and Rill", skillId=1},
        new Skill(188){collection=3, role=Role.TRAVELLER, skillCost=0, dataName="Many Paths to Tread", originalName="Many Paths to Tread", skillId=2},
        new Skill(189){collection=3, role=Role.TRAVELLER, skillCost=0, dataName="Many Paths to Tread", originalName="Many Paths to Tread", skillId=3},
        new Skill(190){collection=3, role=Role.TRAVELLER, skillCost=3, dataName="Camaraderie", originalName="Camaraderie", skillId=4},
        new Skill(191){collection=3, role=Role.TRAVELLER, skillCost=3, dataName="Around Every Corner", originalName="Around Every Corner", skillId=5},
        new Skill(192){collection=3, role=Role.TRAVELLER, skillCost=3, dataName="Seasoned", originalName="Seasoned", skillId=6},
        new Skill(193){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Fleet of Foot", originalName="Fleet of Foot", skillId=7},
        new Skill(194){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Nothing to Fear", originalName="Nothing to Fear", skillId=8},
        new Skill(195){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Campfire Tales", originalName="Campfire Tales", skillId=9},
        new Skill(196){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Paths Less Travelled", originalName="Paths Less Travelled", skillId=10},
        new Skill(197){collection=3, role=Role.TRAVELLER, skillCost=12, dataName="Wanderlust", originalName="Wanderlust", skillId=11},
        new Skill(198){collection=3, role=Role.TRAVELLER, skillCost=12, dataName="Forgotten Roads", originalName="Forgotten Roads", skillId=12},

        new Skill(199){collection=5, role=Role.TRICKSTER, skillCost=0, dataName="Merry Chase", originalName="Merry Chase", skillId=1},
        new Skill(200){collection=5, role=Role.TRICKSTER, skillCost=0, dataName="Chicanery", originalName="Chicanery", skillId=2},
        new Skill(201){collection=5, role=Role.TRICKSTER, skillCost=0, dataName="Chicanery", originalName="Chicanery", skillId=3},
        new Skill(202){collection=5, role=Role.TRICKSTER, skillCost=3, dataName="Clever Distraction", originalName="Clever Distraction", skillId=4},
        new Skill(203){collection=5, role=Role.TRICKSTER, skillCost=3, dataName="Improvisation", originalName="Improvisation", skillId=5},
        new Skill(204){collection=5, role=Role.TRICKSTER, skillCost=3, dataName="Trick up Your Sleeve", originalName="Trick up Your Sleeve", skillId=6},
        new Skill(205){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Cutting Remark", originalName="Cutting Remark", skillId=7},
        new Skill(206){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Gallows Humor", originalName="Gallows Humor", skillId=8},
        new Skill(207){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Look over There!", originalName="Look over There!", skillId=9},
        new Skill(208){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Confusticate", originalName="Confusticate", skillId=10},
        new Skill(209){collection=5, role=Role.TRICKSTER, skillCost=12, dataName="Eye for Opportunity", originalName="Eye for Opportunity", skillId=11},
        new Skill(210){collection=5, role=Role.TRICKSTER, skillCost=12, dataName="Quite a Spectacle", originalName="Quite a Spectacle", skillId=12},

        //Custom Skills
        new Skill(211){collection=7, role=Role.CHIEFTAIN, skillCost=0, dataName="Emissary", originalName="Emissary", skillId=1},
        new Skill(212){collection=7, role=Role.CHIEFTAIN, skillCost=0, dataName="Brotherhood", originalName="Brotherhood", skillId=2},
        new Skill(213){collection=7, role=Role.CHIEFTAIN, skillCost=0, dataName="Brotherhood", originalName="Brotherhood", skillId=3},
        new Skill(214){collection=7, role=Role.CHIEFTAIN, skillCost=3, dataName="Stand and Fight!", originalName="Stand and Fight!", skillId=4},
        new Skill(215){collection=7, role=Role.CHIEFTAIN, skillCost=3, dataName="Common Cause", originalName="Common Cause", skillId=5},
        new Skill(216){collection=7, role=Role.CHIEFTAIN, skillCost=3, dataName="Send a Message", originalName="Send a Message", skillId=6},
        new Skill(217){collection=7, role=Role.CHIEFTAIN, skillCost=7, dataName="Advice", originalName="Advice", skillId=7},
        new Skill(218){collection=7, role=Role.CHIEFTAIN, skillCost=7, dataName="Advice", originalName="Advice", skillId=8},
        new Skill(219){collection=7, role=Role.CHIEFTAIN, skillCost=7, dataName="Combined Efforts", originalName="Combined Efforts", skillId=9},
        new Skill(220){collection=7, role=Role.CHIEFTAIN, skillCost=7, dataName="Song of Memory", originalName="Song of Memory", skillId=10},
        new Skill(221){collection=7, role=Role.CHIEFTAIN, skillCost=12, dataName="Valiant Sacrifice", originalName="Valiant Sacrifice", skillId=11},
        new Skill(222){collection=7, role=Role.CHIEFTAIN, skillCost=12, dataName="Lead the Way", originalName="Lead the Way", skillId=12},

        new Skill(223){collection=7, role=Role.COUNSELOR, skillCost=0, dataName="Counsel", originalName="Counsel", skillId=1},
        new Skill(224){collection=7, role=Role.COUNSELOR, skillCost=0, dataName="Sound Advice", originalName="Sound Advice", skillId=2},
        new Skill(225){collection=7, role=Role.COUNSELOR, skillCost=0, dataName="Sound Advice", originalName="Sound Advice", skillId=3},
        new Skill(226){collection=7, role=Role.COUNSELOR, skillCost=3, dataName="Sharing Wisdom", originalName="Sharing Wisdom", skillId=4},
        new Skill(227){collection=7, role=Role.COUNSELOR, skillCost=3, dataName="Blessing", originalName="Blessing", skillId=5},
        new Skill(228){collection=7, role=Role.COUNSELOR, skillCost=7, dataName="Clairvoyance", originalName="Clairvoyance", skillId=6},
        new Skill(229){collection=7, role=Role.COUNSELOR, skillCost=7, dataName="Song of Encouragement", originalName="Song of Encouragement", skillId=7},
        new Skill(230){collection=7, role=Role.COUNSELOR, skillCost=12, dataName="Safe Haven", originalName="Safe Haven", skillId=8},
        new Skill(231){collection=7, role=Role.COUNSELOR, skillCost=12, dataName="Epiphany", originalName="Epiphany", skillId=9},
        new Skill(232){collection=7, role=Role.COUNSELOR, skillCost=16, dataName="Council of War", originalName="Council of War", skillId=10},
        new Skill(233){collection=7, role=Role.COUNSELOR, skillCost=16, dataName="Messenger", originalName="Messenger", skillId=11},
        new Skill(234){collection=7, role=Role.COUNSELOR, skillCost=20, dataName="The White Council", originalName="The White Council", skillId=12},

        new Skill(235){collection=7, role=Role.DARKFIGHTER, skillCost=0, dataName="Dim Glow", originalName="Dim Glow", skillId=1},
        new Skill(236){collection=7, role=Role.DARKFIGHTER, skillCost=0, dataName="Glimmering Blade", originalName="Glimmering Blade", skillId=2},
        new Skill(237){collection=7, role=Role.DARKFIGHTER, skillCost=0, dataName="Radiant Defence", originalName="Radiant Defence", skillId=3},
        new Skill(238){collection=7, role=Role.DARKFIGHTER, skillCost=3, dataName="Trick of the Light", originalName="Trick of the Light", skillId=4},
        new Skill(239){collection=7, role=Role.DARKFIGHTER, skillCost=3, dataName="Dark Rumours", originalName="Dark Rumours", skillId=5},
        new Skill(240){collection=7, role=Role.DARKFIGHTER, skillCost=3, dataName="Concentration", originalName="Concentration", skillId=6},
        new Skill(241){collection=7, role=Role.DARKFIGHTER, skillCost=7, dataName="Step into the Gloom", originalName="Step into the Gloom", skillId=7},
        new Skill(242){collection=7, role=Role.DARKFIGHTER, skillCost=7, dataName="Fearlessness", originalName="Fearlessness", skillId=8},
        new Skill(243){collection=7, role=Role.DARKFIGHTER, skillCost=7, dataName="Focused Fury", originalName="Focused Fury", skillId=9},
        new Skill(244){collection=7, role=Role.DARKFIGHTER, skillCost=7, dataName="Shrinking Shades", originalName="Shrinking Shades", skillId=10},
        new Skill(245){collection=7, role=Role.DARKFIGHTER, skillCost=12, dataName="Rays of Noon", originalName="Rays of Noon", skillId=11},
        new Skill(246){collection=7, role=Role.DARKFIGHTER, skillCost=12, dataName="Cast the Shadows", originalName="Cast the Shadows", skillId=12},

        new Skill(247){collection=7, role=Role.DEFENDER, skillCost=0, dataName="Ready for Battle", originalName="Ready for Battle", skillId=1},
        new Skill(248){collection=7, role=Role.DEFENDER, skillCost=0, dataName="Stand United", originalName="Stand United", skillId=2},
        new Skill(249){collection=7, role=Role.DEFENDER, skillCost=0, dataName="Stand United", originalName="Stand United", skillId=3},
        new Skill(250){collection=7, role=Role.DEFENDER, skillCost=3, dataName="Cover the Escape", originalName="Cover the Escape", skillId=4},
        new Skill(251){collection=7, role=Role.DEFENDER, skillCost=3, dataName="Cautious Advance", originalName="Cautious Advance", skillId=5},
        new Skill(252){collection=7, role=Role.DEFENDER, skillCost=3, dataName="Spiked Armor", originalName="Spiked Armor", skillId=6},
        new Skill(253){collection=7, role=Role.DEFENDER, skillCost=7, dataName="Nature's Defense", originalName="Nature's Defense", skillId=7},
        new Skill(254){collection=7, role=Role.DEFENDER, skillCost=7, dataName="Bent not Broken", originalName="Bent not Broken", skillId=8},
        new Skill(255){collection=7, role=Role.DEFENDER, skillCost=7, dataName="Challenging Roar", originalName="Challenging Roar", skillId=9},
        new Skill(256){collection=7, role=Role.DEFENDER, skillCost=7, dataName="Rapid Response", originalName="Rapid Response", skillId=10},
        new Skill(257){collection=7, role=Role.DEFENDER, skillCost=12, dataName="Honor and Duty", originalName="Honor and Duty", skillId=11},
        new Skill(258){collection=7, role=Role.DEFENDER, skillCost=12, dataName="Turn the Tides", originalName="Turn the Tides", skillId=12},

        new Skill(259){collection=7, role=Role.GARDENER, skillCost=0, dataName="Love of the Earth", originalName="Love of the Earth", skillId=1},
        new Skill(260){collection=7, role=Role.GARDENER, skillCost=0, dataName="Farming", originalName="Farming", skillId=2},
        new Skill(261){collection=7, role=Role.GARDENER, skillCost=0, dataName="Farming", originalName="Farming", skillId=3},
        new Skill(262){collection=7, role=Role.GARDENER, skillCost=3, dataName="Smell the Flowers", originalName="Smell the Flowers", skillId=4},
        new Skill(263){collection=7, role=Role.GARDENER, skillCost=3, dataName="Smell the Flowers", originalName="Smell the Flowers", skillId=5},
        new Skill(264){collection=7, role=Role.GARDENER, skillCost=3, dataName="Smell the Flowers", originalName="Smell the Flowers", skillId=6},
        new Skill(265){collection=7, role=Role.GARDENER, skillCost=7, dataName="Plant a Garden", originalName="Plant a Garden", skillId=7},
        new Skill(266){collection=7, role=Role.GARDENER, skillCost=7, dataName="Plant a Garden", originalName="Plant a Garden", skillId=8},
        new Skill(267){collection=7, role=Role.GARDENER, skillCost=7, dataName="Speaking to the Earth", originalName="Speaking to the Earth", skillId=9},
        new Skill(268){collection=7, role=Role.GARDENER, skillCost=7, dataName="Speaking to the Earth", originalName="Speaking to the Earth", skillId=10},
        new Skill(269){collection=7, role=Role.GARDENER, skillCost=12, dataName="Box of Earth", originalName="Box of Earth", skillId=11},
        new Skill(270){collection=7, role=Role.GARDENER, skillCost=12, dataName="Box of Earth", originalName="Box of Earth", skillId=12},

        new Skill(271){collection=7, role=Role.HORSE_LORD, skillCost=0, dataName="Royal Bloodlines", originalName="Royal Bloodlines", skillId=1},
        new Skill(272){collection=7, role=Role.HORSE_LORD, skillCost=0, dataName="Reform the Ranks", originalName="Reform the Ranks", skillId=2},
        new Skill(273){collection=7, role=Role.HORSE_LORD, skillCost=0, dataName="Reform the Ranks", originalName="Reform the Ranks", skillId=3},
        new Skill(274){collection=7, role=Role.HORSE_LORD, skillCost=3, dataName="Surefooted", originalName="Surefooted", skillId=4},
        new Skill(275){collection=7, role=Role.HORSE_LORD, skillCost=3, dataName="Preparation", originalName="Preparation", skillId=5},
        new Skill(276){collection=7, role=Role.HORSE_LORD, skillCost=3, dataName="Healing Presence", originalName="Healing Presence", skillId=6},
        new Skill(277){collection=7, role=Role.HORSE_LORD, skillCost=7, dataName="Battle Hardened", originalName="Battle Hardened", skillId=7},
        new Skill(278){collection=7, role=Role.HORSE_LORD, skillCost=7, dataName="Lifelong Bond", originalName="Lifelong Bond", skillId=8},
        new Skill(279){collection=7, role=Role.HORSE_LORD, skillCost=7, dataName="Rallying Cry", originalName="Rallying Cry", skillId=9},
        new Skill(280){collection=7, role=Role.HORSE_LORD, skillCost=12, dataName="To the King!", originalName="To the King!", skillId=10},
        new Skill(281){collection=7, role=Role.HORSE_LORD, skillCost=12, dataName="The Sun Rises", originalName="The Sun Rises", skillId=11},
        new Skill(282){collection=7, role=Role.HORSE_LORD, skillCost=12, dataName="Forth Eorlingas!", originalName="Forth Eorlingas!", skillId=12},

        new Skill(283){collection=7, role=Role.RANGER, skillCost=0, dataName="Roaming", originalName="Roaming", skillId=1},
        new Skill(284){collection=7, role=Role.RANGER, skillCost=0, dataName="Track the Enemy", originalName="Track the Enemy", skillId=2},
        new Skill(285){collection=7, role=Role.RANGER, skillCost=0, dataName="Track the Enemy", originalName="Track the Enemy", skillId=3},
        new Skill(286){collection=7, role=Role.RANGER, skillCost=3, dataName="Hunting Dogs", originalName="Hunting Dogs", skillId=4},
        new Skill(287){collection=7, role=Role.RANGER, skillCost=3, dataName="Woodland Traps", originalName="Woodland Traps", skillId=5},
        new Skill(288){collection=7, role=Role.RANGER, skillCost=3, dataName="Bivouac", originalName="Bivouac", skillId=6},
        new Skill(289){collection=7, role=Role.RANGER, skillCost=7, dataName="Scout Ahead", originalName="Scout Ahead", skillId=7},
        new Skill(290){collection=7, role=Role.RANGER, skillCost=7, dataName="Knowledge of Trails", originalName="Knowledge of Trails", skillId=8},
        new Skill(291){collection=7, role=Role.RANGER, skillCost=7, dataName="Love of Nature", originalName="Love of Nature", skillId=9},
        new Skill(292){collection=7, role=Role.RANGER, skillCost=7, dataName="Wilderness", originalName="Wilderness", skillId=10},
        new Skill(293){collection=7, role=Role.RANGER, skillCost=12, dataName="Communing with Nature", originalName="Communing with Nature", skillId=11},
        new Skill(294){collection=7, role=Role.RANGER, skillCost=12, dataName="Ranger Prowess", originalName="Ranger Prowess", skillId=12},

        new Skill(295){collection=7, role=Role.RINGBEARER, skillCost=0, dataName="The One Ring", originalName="The One Ring", skillId=1},
        new Skill(296){collection=7, role=Role.RINGBEARER, skillCost=0, dataName="It is a Gift", originalName="It is a Gift", skillId=2},
        new Skill(297){collection=7, role=Role.RINGBEARER, skillCost=0, dataName="It is a Gift", originalName="It is a Gift", skillId=3},
        new Skill(298){collection=7, role=Role.RINGBEARER, skillCost=3, dataName="You Cannot Wield It!", originalName="You Cannot Wield It!", skillId=4},
        new Skill(299){collection=7, role=Role.RINGBEARER, skillCost=3, dataName="Isildur's Bane", originalName="Isildur's Bane", skillId=5},
        new Skill(300){collection=7, role=Role.RINGBEARER, skillCost=3, dataName="Precious to Me", originalName="Precious to Me", skillId=6},
        new Skill(301){collection=7, role=Role.RINGBEARER, skillCost=7, dataName="Three Rings for the Elven Kings", originalName="Three Rings for the Elven Kings", skillId=7},
        new Skill(302){collection=7, role=Role.RINGBEARER, skillCost=7, dataName="Seven for the Dwarf-Lords", originalName="Seven for the Dwarf-Lords", skillId=8},
        new Skill(303){collection=7, role=Role.RINGBEARER, skillCost=7, dataName="Nine for Mortal Men", originalName="Nine for Mortal Men", skillId=9},
        new Skill(304){collection=7, role=Role.RINGBEARER, skillCost=7, dataName="One for the Dark Lord", originalName="One for the Dark Lord", skillId=10},
        new Skill(305){collection=7, role=Role.RINGBEARER, skillCost=12, dataName="In the Land of Mordor", originalName="In the Land of Mordor", skillId=11},
        new Skill(306){collection=7, role=Role.RINGBEARER, skillCost=12, dataName="Where the Shadows Lie", originalName="Where the Shadows Lie", skillId=12},

        new Skill(307){collection=7, role=Role.RING_BEARER, skillCost=0, dataName="The One", originalName="The One", skillId=1},
        new Skill(308){collection=7, role=Role.RING_BEARER, skillCost=0, dataName="Eye of Sauron", originalName="Eye of Sauron", skillId=2},
        new Skill(309){collection=7, role=Role.RING_BEARER, skillCost=0, dataName="Eye of Sauron", originalName="Eye of Sauron", skillId=3},
        new Skill(310){collection=7, role=Role.RING_BEARER, skillCost=3, dataName="Narya", originalName="Narya", skillId=4},
        new Skill(311){collection=7, role=Role.RING_BEARER, skillCost=3, dataName="Nenya", originalName="Nenya", skillId=5},
        new Skill(312){collection=7, role=Role.RING_BEARER, skillCost=3, dataName="Vilya", originalName="Vilya", skillId=6},
        new Skill(313){collection=7, role=Role.RING_BEARER, skillCost=7, dataName="Deeper into Darkness", originalName="Deeper into Darkness", skillId=7},
        new Skill(314){collection=7, role=Role.RING_BEARER, skillCost=7, dataName="Face Your Fear", originalName="Face Your Fear", skillId=8},
        new Skill(315){collection=7, role=Role.RING_BEARER, skillCost=7, dataName="Fly You Fools!", originalName="Fly You Fools!", skillId=9},
        new Skill(316){collection=7, role=Role.RING_BEARER, skillCost=12, dataName="Bleak Hope", originalName="Bleak Hope", skillId=10},
        new Skill(317){collection=7, role=Role.RING_BEARER, skillCost=12, dataName="Fellowship", originalName="Fellowship", skillId=11},
        new Skill(318){collection=7, role=Role.RING_BEARER, skillCost=16, dataName="Cast It into the Fire!", originalName="Cast It into the Fire!", skillId=12},

        new Skill(319){collection=7, role=Role.SHEPHERD, skillCost=0, dataName="Lost and Found", originalName="Lost and Found", skillId=1},
        new Skill(320){collection=7, role=Role.SHEPHERD, skillCost=0, dataName="Together We Stand", originalName="Together We Stand", skillId=2},
        new Skill(321){collection=7, role=Role.SHEPHERD, skillCost=3, dataName="Spirit beyond Compare", originalName="Spirit beyond Compare", skillId=3},
        new Skill(322){collection=7, role=Role.SHEPHERD, skillCost=6, dataName="Patience", originalName="Patience", skillId=4},
        new Skill(323){collection=7, role=Role.SHEPHERD, skillCost=8, dataName="Keeping Watch", originalName="Keeping Watch", skillId=5},
        new Skill(324){collection=7, role=Role.SHEPHERD, skillCost=8, dataName="Vigilance", originalName="Vigilance", skillId=6},

        new Skill(325){collection=7, role=Role.TRACKER, skillCost=0, dataName="Pursuit", originalName="Pursuit", skillId=1},
        new Skill(326){collection=7, role=Role.TRACKER, skillCost=0, dataName="Speaking to the Earth", originalName="Speaking to the Earth", skillId=2},
        new Skill(327){collection=7, role=Role.TRACKER, skillCost=0, dataName="Speaking to the Earth", originalName="Speaking to the Earth", skillId=3},
        new Skill(328){collection=7, role=Role.TRACKER, skillCost=3, dataName="Hidden Ways", originalName="Hidden Ways", skillId=4},
        new Skill(329){collection=7, role=Role.TRACKER, skillCost=3, dataName="Element of Surprise", originalName="Element of Surprise", skillId=5},
        new Skill(330){collection=7, role=Role.TRACKER, skillCost=3, dataName="Pursuit", originalName="Pursuit", skillId=6},
        new Skill(331){collection=7, role=Role.TRACKER, skillCost=7, dataName="Tracks in the Mud", originalName="Tracks in the Mud", skillId=7},
        new Skill(332){collection=7, role=Role.TRACKER, skillCost=7, dataName="Thrill of the Chase", originalName="Thrill of the Chase", skillId=8},
        new Skill(333){collection=7, role=Role.TRACKER, skillCost=7, dataName="Coney in a Trap", originalName="Coney in a Trap", skillId=9},
        new Skill(334){collection=7, role=Role.TRACKER, skillCost=7, dataName="Interrogation", originalName="Interrogation", skillId=10},
        new Skill(335){collection=7, role=Role.TRACKER, skillCost=12, dataName="Forest Snare", originalName="Forest Snare", skillId=11},
        new Skill(336){collection=7, role=Role.TRACKER, skillCost=12, dataName="Subdued", originalName="Subdued", skillId=12},

        new Skill(337){collection=7, role=Role.SEER, skillCost=0, dataName="Look Beyond", originalName="Look Beyond", skillId=1},
        new Skill(338){collection=7, role=Role.SEER, skillCost=0, dataName="Threat Foreseen", originalName="Threat Foreseen", skillId=2},
        new Skill(339){collection=7, role=Role.SEER, skillCost=0, dataName="Threat Foreseen", originalName="Threat Foreseen", skillId=3},
        new Skill(340){collection=7, role=Role.SEER, skillCost=3, dataName="Whispers of Vairë", originalName="Whispers of Vairë", skillId=4},
        new Skill(341){collection=7, role=Role.SEER, skillCost=3, dataName="Grave Peril", originalName="Grave Peril", skillId=5},
        new Skill(342){collection=7, role=Role.SEER, skillCost=3, dataName="Tramp of Doom", originalName="Tramp of Doom", skillId=6},
        new Skill(343){collection=7, role=Role.SEER, skillCost=7, dataName="Mirror of Gladriel", originalName="Mirror of Gladriel", skillId=7},
        new Skill(344){collection=7, role=Role.SEER, skillCost=7, dataName="Recognize Necessity", originalName="Recognize Necessity", skillId=8},
        new Skill(345){collection=7, role=Role.SEER, skillCost=7, dataName="Stroke of Fate", originalName="Stroke of Fate", skillId=9},
        new Skill(346){collection=7, role=Role.SEER, skillCost=7, dataName="As Foretold", originalName="As Foretold", skillId=10},
        new Skill(347){collection=7, role=Role.SEER, skillCost=12, dataName="The World is Changing", originalName="The World is Changing", skillId=11},
        new Skill(348){collection=7, role=Role.SEER, skillCost=12, dataName="Grim Insight", originalName="Grim Insight", skillId=12},

        new Skill(349){collection=7, role=Role.WARRIOR, skillCost=0, dataName="Stamina", originalName="Stamina", skillId=1},
        new Skill(350){collection=7, role=Role.WARRIOR, skillCost=0, dataName="Driven to Battle", originalName="Driven to Battle", skillId=2},
        new Skill(351){collection=7, role=Role.WARRIOR, skillCost=0, dataName="Driven to Battle", originalName="Driven to Battle", skillId=3},
        new Skill(352){collection=7, role=Role.WARRIOR, skillCost=3, dataName="Steel Resolve", originalName="Steel Resolve", skillId=4},
        new Skill(353){collection=7, role=Role.WARRIOR, skillCost=3, dataName="Peaceful Sanctuary", originalName="Peaceful Sanctuary", skillId=5},
        new Skill(354){collection=7, role=Role.WARRIOR, skillCost=3, dataName="Rallying Cry", originalName="Rallying Cry", skillId=6},
        new Skill(355){collection=7, role=Role.WARRIOR, skillCost=7, dataName="Back against the Wall", originalName="Back against the Wall", skillId=7},
        new Skill(356){collection=7, role=Role.WARRIOR, skillCost=7, dataName="Battle Fury", originalName="Battle Fury", skillId=8},
        new Skill(357){collection=7, role=Role.WARRIOR, skillCost=7, dataName="Fierce Attack", originalName="Fierce Attack", skillId=9},
        new Skill(358){collection=7, role=Role.WARRIOR, skillCost=7, dataName="Gather Information", originalName="Gather Information", skillId=10},
        new Skill(359){collection=7, role=Role.WARRIOR, skillCost=12, dataName="Stand in the Breach", originalName="Stand in the Breach", skillId=11},
        new Skill(360){collection=7, role=Role.WARRIOR, skillCost=12, dataName="Aurë Entuluva", originalName="Aurë Entuluva", skillId=12},
    };
}
