using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


public class Skills
{
    public static Skill FromID(int id)
    {
        return list[id];
    }

    public static Skill SkillFromRoleID(Role role, int skillId)
    {
        Skill skill = list.FirstOrDefault(it => it.role == role && it.skillId == skillId);
        if(skill == null) { skill = list[0]; } //Set to None as default
        return skill;
    }

    public static readonly List<Skill> list = new List<Skill>
    {
        new Skill(0){collection=0, role=Role.NONE, skillCost=0, dataName="None", originalName="None", skillId=0},
        new Skill(1){collection=6, role=Role.BEAST_FRIEND, skillCost=0, dataName="Chittering Mouse", originalName="Chittering Mouse", skillId=1},
        new Skill(2){collection=6, role=Role.BEAST_FRIEND, skillCost=0, dataName="Nightingale", originalName="Nightingale", skillId=2},
        new Skill(3){collection=6, role=Role.BEAST_FRIEND, skillCost=6, dataName="Pet Rabbit", originalName="Pet Rabbit", skillId=3},
        new Skill(4){collection=6, role=Role.BEAST_FRIEND, skillCost=6, dataName="Band of Squirrels", originalName="Band of Squirrels", skillId=4},
        new Skill(5){collection=6, role=Role.BEAST_FRIEND, skillCost=8, dataName="Iron Hills Goat", originalName="Iron Hills Goat", skillId=5},
        new Skill(6){collection=6, role=Role.BEAST_FRIEND, skillCost=8, dataName="[Lome-TG]", originalName="Lómë", skillId=6},
        new Skill(7){collection=1, role=Role.BURGLAR, skillCost=0, dataName="Self-Sufficient", originalName="Self-Sufficient", skillId=1},
        new Skill(8){collection=1, role=Role.BURGLAR, skillCost=0, dataName="Quiet", originalName="Quiet", skillId=2},
        new Skill(9){collection=1, role=Role.BURGLAR, skillCost=0, dataName="Quiet", originalName="Quiet", skillId=3},
        new Skill(10){collection=1, role=Role.BURGLAR, skillCost=3, dataName="Word of Fortune", originalName="Word of Fortune", skillId=4},
        new Skill(11){collection=1, role=Role.BURGLAR, skillCost=3, dataName="Sneaking", originalName="Sneaking", skillId=5},
        new Skill(12){collection=1, role=Role.BURGLAR, skillCost=3, dataName="Pockets", originalName="Pockets", skillId=6},
        new Skill(13){collection=1, role=Role.BURGLAR, skillCost=7, dataName="What Is In my Pocket?", originalName="What Is In my Pocket?", skillId=7},
        new Skill(14){collection=1, role=Role.BURGLAR, skillCost=7, dataName="Self-Sufficient", originalName="Self-Sufficient", skillId=8},
        new Skill(15){collection=1, role=Role.BURGLAR, skillCost=7, dataName="Hidden Blades", originalName="Hidden Blades", skillId=9},
        new Skill(16){collection=1, role=Role.BURGLAR, skillCost=7, dataName="Unseen Strike", originalName="Unseen Strike", skillId=10},
        new Skill(17){collection=1, role=Role.BURGLAR, skillCost=12, dataName="Quick Thinking", originalName="Quick Thinking", skillId=11},
        new Skill(18){collection=1, role=Role.BURGLAR, skillCost=12, dataName="Embrace the Darkness", originalName="Embrace the Darkness", skillId=12},
        new Skill(19){collection=1, role=Role.CAPTAIN, skillCost=0, dataName="Well Provisioned", originalName="Well Provisioned", skillId=1},
        new Skill(20){collection=1, role=Role.CAPTAIN, skillCost=0, dataName="Lead the Charge", originalName="Lead the Charge", skillId=2},
        new Skill(21){collection=1, role=Role.CAPTAIN, skillCost=0, dataName="Lead the Charge", originalName="Lead the Charge", skillId=3},
        new Skill(22){collection=1, role=Role.CAPTAIN, skillCost=3, dataName="Word of Triumph", originalName="Word of Triumph", skillId=4},
        new Skill(23){collection=1, role=Role.CAPTAIN, skillCost=3, dataName="Stand Together", originalName="Stand Together", skillId=5},
        new Skill(24){collection=1, role=Role.CAPTAIN, skillCost=3, dataName="A Fey Mood", originalName="A Fey Mood", skillId=6},
        new Skill(25){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="Empowering Words", originalName="Empowering Words", skillId=7},
        new Skill(26){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="Inspiring Presence", originalName="Inspiring Presence", skillId=8},
        new Skill(27){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="To Me!", originalName="To Me!", skillId=9},
        new Skill(28){collection=1, role=Role.CAPTAIN, skillCost=7, dataName="Battle Plan", originalName="Battle Plan", skillId=10},
        new Skill(29){collection=1, role=Role.CAPTAIN, skillCost=12, dataName="A Wind Among Grass", originalName="A Wind Among Grass", skillId=11},
        new Skill(30){collection=1, role=Role.CAPTAIN, skillCost=12, dataName="Master Tactician", originalName="Master Tactician", skillId=12},
        new Skill(31){collection=3, role=Role.DELVER, skillCost=0, dataName="Intrepid", originalName="Intrepid", skillId=1},
        new Skill(32){collection=3, role=Role.DELVER, skillCost=0, dataName="Shadow Sight", originalName="Shadow Sight", skillId=2},
        new Skill(33){collection=3, role=Role.DELVER, skillCost=0, dataName="Shadow Sight", originalName="Shadow Sight", skillId=3},
        new Skill(34){collection=3, role=Role.DELVER, skillCost=3, dataName="Wiles", originalName="Wiles", skillId=4},
        new Skill(35){collection=3, role=Role.DELVER, skillCost=3, dataName="Crushing Blow", originalName="Crushing Blow", skillId=5},
        new Skill(36){collection=3, role=Role.DELVER, skillCost=3, dataName="Boasting", originalName="Boasting", skillId=6},
        new Skill(37){collection=3, role=Role.DELVER, skillCost=7, dataName="Forging Ahead", originalName="Forging Ahead", skillId=7},
        new Skill(38){collection=3, role=Role.DELVER, skillCost=7, dataName="Spirit of Adventure", originalName="Spirit of Adventure", skillId=8},
        new Skill(39){collection=3, role=Role.DELVER, skillCost=7, dataName="No Stone Unturned", originalName="No Stone Unturned", skillId=9},
        new Skill(40){collection=3, role=Role.DELVER, skillCost=7, dataName="No Stone Unturned", originalName="No Stone Unturned", skillId=10},
        new Skill(41){collection=3, role=Role.DELVER, skillCost=12, dataName="Glory", originalName="Glory", skillId=11},
        new Skill(42){collection=3, role=Role.DELVER, skillCost=12, dataName="Treasures Untold", originalName="Treasures Untold", skillId=12},
        new Skill(43){collection=1, role=Role.GUARDIAN, skillCost=0, dataName="You Cannot Pass", originalName="You Cannot Pass", skillId=1},
        new Skill(44){collection=1, role=Role.GUARDIAN, skillCost=0, dataName="Ready Defense", originalName="Ready Defense", skillId=2},
        new Skill(45){collection=1, role=Role.GUARDIAN, skillCost=0, dataName="Ready Defense", originalName="Ready Defense", skillId=3},
        new Skill(46){collection=1, role=Role.GUARDIAN, skillCost=3, dataName="Word of Glory", originalName="Word of Glory", skillId=4},
        new Skill(47){collection=1, role=Role.GUARDIAN, skillCost=3, dataName="Noble Sacrifice", originalName="Noble Sacrifice", skillId=5},
        new Skill(48){collection=1, role=Role.GUARDIAN, skillCost=3, dataName="Desperate Defense", originalName="Desperate Defense", skillId=6},
        new Skill(49){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Voice Like Ringing Steel", originalName="Voice Like Ringing Steel", skillId=7},
        new Skill(50){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Ready Defense", originalName="Ready Defense", skillId=8},
        new Skill(51){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Guarded Strike", originalName="Guarded Strike", skillId=9},
        new Skill(52){collection=1, role=Role.GUARDIAN, skillCost=7, dataName="Grim Resolve", originalName="Grim Resolve", skillId=10},
        new Skill(53){collection=1, role=Role.GUARDIAN, skillCost=12, dataName="Final Defense", originalName="Final Defense", skillId=11},
        new Skill(54){collection=1, role=Role.GUARDIAN, skillCost=12, dataName="Defense Instruction", originalName="Defense Instruction", skillId=12},
        new Skill(55){collection=5, role=Role.GUIDE, skillCost=0, dataName="Great Hound", originalName="Great Hound", skillId=1},
        new Skill(56){collection=5, role=Role.GUIDE, skillCost=0, dataName="The Way Forward", originalName="The Way Forward", skillId=2},
        new Skill(57){collection=5, role=Role.GUIDE, skillCost=0, dataName="The Way Forward", originalName="The Way Forward", skillId=3},
        new Skill(58){collection=5, role=Role.GUIDE, skillCost=3, dataName="Helping Hand", originalName="Helping Hand", skillId=4},
        new Skill(59){collection=5, role=Role.GUIDE, skillCost=3, dataName="Point the Way", originalName="Point the Way", skillId=5},
        new Skill(60){collection=5, role=Role.GUIDE, skillCost=3, dataName="Lead by Example", originalName="Lead by Example", skillId=6},
        new Skill(61){collection=5, role=Role.GUIDE, skillCost=7, dataName="Alert", originalName="Alert", skillId=7},
        new Skill(62){collection=5, role=Role.GUIDE, skillCost=7, dataName="Ancient Trails", originalName="Ancient Trails", skillId=8},
        new Skill(63){collection=5, role=Role.GUIDE, skillCost=7, dataName="Teamwork", originalName="Teamwork", skillId=9},
        new Skill(64){collection=5, role=Role.GUIDE, skillCost=7, dataName="Survival Training", originalName="Survival Training", skillId=10},
        new Skill(65){collection=5, role=Role.GUIDE, skillCost=12, dataName="All Together", originalName="All Together", skillId=11},
        new Skill(66){collection=5, role=Role.GUIDE, skillCost=12, dataName="Timely Assistance", originalName="Timely Assistance", skillId=12},
        new Skill(67){collection=3, role=Role.HERBALIST, skillCost=0, dataName="Curiosity", originalName="Curiosity", skillId=1},
        new Skill(68){collection=3, role=Role.HERBALIST, skillCost=0, dataName="Gathered Wisdom", originalName="Gathered Wisdom", skillId=2},
        new Skill(69){collection=3, role=Role.HERBALIST, skillCost=0, dataName="Gathered Wisdom", originalName="Gathered Wisdom", skillId=3},
        new Skill(70){collection=3, role=Role.HERBALIST, skillCost=3, dataName="Study of Nature", originalName="Study of Nature", skillId=4},
        new Skill(71){collection=3, role=Role.HERBALIST, skillCost=3, dataName="Hands of a Healer", originalName="Hands of a Healer", skillId=5},
        new Skill(72){collection=3, role=Role.HERBALIST, skillCost=3, dataName="Insight", originalName="Insight", skillId=6},
        new Skill(73){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Calming Presence", originalName="Calming Presence", skillId=7},
        new Skill(74){collection=3, role=Role.HERBALIST, skillCost=7, dataName="[Aid-at-last]", originalName="Athelas", skillId=8},
        new Skill(75){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Natural Remedy", originalName="Natural Remedy", skillId=9},
        new Skill(76){collection=3, role=Role.HERBALIST, skillCost=7, dataName="Innovation", originalName="Innovation", skillId=10},
        new Skill(77){collection=3, role=Role.HERBALIST, skillCost=12, dataName="Phosphorescence", originalName="Phosphorescence", skillId=11},
        new Skill(78){collection=3, role=Role.HERBALIST, skillCost=12, dataName="Healing Poultice", originalName="Healing Poultice", skillId=12},
        new Skill(79){collection=1, role=Role.HUNTER, skillCost=0, dataName="Resourceful", originalName="Resourceful", skillId=1},
        new Skill(80){collection=1, role=Role.HUNTER, skillCost=0, dataName="Precise Strike", originalName="Precise Strike", skillId=2},
        new Skill(81){collection=1, role=Role.HUNTER, skillCost=0, dataName="Precise Strike", originalName="Precise Strike", skillId=3},
        new Skill(82){collection=1, role=Role.HUNTER, skillCost=3, dataName="Resourceful", originalName="Resourceful", skillId=4},
        new Skill(83){collection=1, role=Role.HUNTER, skillCost=3, dataName="Coordinated Strike", originalName="Coordinated Strike", skillId=5},
        new Skill(84){collection=1, role=Role.HUNTER, skillCost=3, dataName="Quick Snare", originalName="Quick Snare", skillId=6},
        new Skill(85){collection=1, role=Role.HUNTER, skillCost=7, dataName="Death Stroke", originalName="Death Stroke", skillId=7},
        new Skill(86){collection=1, role=Role.HUNTER, skillCost=7, dataName="Barrage", originalName="Barrage", skillId=8},
        new Skill(87){collection=1, role=Role.HUNTER, skillCost=7, dataName="Falcon Companion", originalName="Falcon Companion", skillId=9},
        new Skill(88){collection=1, role=Role.HUNTER, skillCost=7, dataName="Gather Supplies", originalName="Gather Supplies", skillId=10},
        new Skill(89){collection=1, role=Role.HUNTER, skillCost=12, dataName="On the Hunt", originalName="On the Hunt", skillId=11},
        new Skill(90){collection=1, role=Role.HUNTER, skillCost=12, dataName="Stalk Prey", originalName="Stalk Prey", skillId=12},
        new Skill(91){collection=5, role=Role.LOREKEEPER, skillCost=0, dataName="Preparation", originalName="Preparation", skillId=1},
        new Skill(92){collection=5, role=Role.LOREKEEPER, skillCost=0, dataName="Childhood Tales", originalName="Childhood Tales", skillId=2},
        new Skill(93){collection=5, role=Role.LOREKEEPER, skillCost=0, dataName="Childhood Tales", originalName="Childhood Tales", skillId=3},
        new Skill(94){collection=5, role=Role.LOREKEEPER, skillCost=3, dataName="Driven by Knowedge", originalName="Driven by Knowedge", skillId=4},
        new Skill(95){collection=5, role=Role.LOREKEEPER, skillCost=3, dataName="Wisdom beyond Years", originalName="Wisdom beyond Years", skillId=5},
        new Skill(96){collection=5, role=Role.LOREKEEPER, skillCost=3, dataName="Wit beyond Measure", originalName="Wit beyond Measure", skillId=6},
        new Skill(97){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Ancestry", originalName="Ancestry", skillId=7},
        new Skill(98){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Collector", originalName="Collector", skillId=8},
        new Skill(99){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Secrets of the Wide World", originalName="Secrets of the Wide World", skillId=9},
        new Skill(100){collection=5, role=Role.LOREKEEPER, skillCost=7, dataName="Song of History", originalName="Song of History", skillId=10},
        new Skill(101){collection=5, role=Role.LOREKEEPER, skillCost=12, dataName="Keeper of the Chronicle", originalName="Keeper of the Chronicle", skillId=11},
        new Skill(102){collection=5, role=Role.LOREKEEPER, skillCost=12, dataName="Exploit Weakness", originalName="Exploit Weakness", skillId=12},
        new Skill(103){collection=3, role=Role.MEDDLER, skillCost=0, dataName="Nosy", originalName="Nosy", skillId=1},
        new Skill(104){collection=3, role=Role.MEDDLER, skillCost=0, dataName="Guidance", originalName="Guidance", skillId=2},
        new Skill(105){collection=3, role=Role.MEDDLER, skillCost=0, dataName="Guidance", originalName="Guidance", skillId=3},
        new Skill(106){collection=3, role=Role.MEDDLER, skillCost=3, dataName="Gossip", originalName="Gossip", skillId=4},
        new Skill(107){collection=3, role=Role.MEDDLER, skillCost=3, dataName="Fast Talking", originalName="Fast Talking", skillId=5},
        new Skill(108){collection=3, role=Role.MEDDLER, skillCost=7, dataName="Interfering", originalName="Interfering", skillId=6},
        new Skill(109){collection=3, role=Role.MEDDLER, skillCost=7, dataName="Ancient Legend", originalName="Ancient Legend", skillId=7},
        new Skill(110){collection=3, role=Role.MEDDLER, skillCost=12, dataName="Contemplation", originalName="Contemplation", skillId=8},
        new Skill(111){collection=3, role=Role.MEDDLER, skillCost=12, dataName="Flattery", originalName="Flattery", skillId=9},
        new Skill(112){collection=3, role=Role.MEDDLER, skillCost=12, dataName="Hidden Plans", originalName="Hidden Plans", skillId=10},
        new Skill(113){collection=3, role=Role.MEDDLER, skillCost=16, dataName="Quick Temper", originalName="Quick Temper", skillId=11},
        new Skill(114){collection=3, role=Role.MEDDLER, skillCost=16, dataName="Strong Opinions", originalName="Strong Opinions", skillId=12},
        new Skill(115){collection=1, role=Role.MUSICIAN, skillCost=0, dataName="Endless Melody", originalName="Endless Melody", skillId=1},
        new Skill(116){collection=1, role=Role.MUSICIAN, skillCost=0, dataName="Travelling Song", originalName="Travelling Song", skillId=2},
        new Skill(117){collection=1, role=Role.MUSICIAN, skillCost=0, dataName="Travelling Song", originalName="Travelling Song", skillId=3},
        new Skill(118){collection=1, role=Role.MUSICIAN, skillCost=3, dataName="Word of Peace", originalName="Word of Peace", skillId=4},
        new Skill(119){collection=1, role=Role.MUSICIAN, skillCost=3, dataName="Song of Mocking", originalName="Song of Mocking", skillId=5},
        new Skill(120){collection=1, role=Role.MUSICIAN, skillCost=3, dataName="A Bit of Nonsense", originalName="A Bit of Nonsense", skillId=6},
        new Skill(121){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Endless Wonder", originalName="Endless Wonder", skillId=7},
        new Skill(122){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="[Durham]'s Song", originalName="Durin's Song", skillId=8},
        new Skill(123){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Lay of [Nimrod]", originalName="Lay of Nimrodel", skillId=9},
        new Skill(124){collection=1, role=Role.MUSICIAN, skillCost=7, dataName="Burst Into Song", originalName="Burst Into Song", skillId=10},
        new Skill(125){collection=1, role=Role.MUSICIAN, skillCost=12, dataName="Crescendo of Dawn", originalName="Crescendo of Dawn", skillId=11},
        new Skill(126){collection=1, role=Role.MUSICIAN, skillCost=12, dataName="Tale of [Snuviel]", originalName="Tale of Tinuviel", skillId=12},
        new Skill(127){collection=1, role=Role.PATHFINDER, skillCost=0, dataName="Trailblazer", originalName="Trailblazer", skillId=1},
        new Skill(128){collection=1, role=Role.PATHFINDER, skillCost=0, dataName="Paths Unseen", originalName="Paths Unseen", skillId=2},
        new Skill(129){collection=1, role=Role.PATHFINDER, skillCost=0, dataName="Paths Unseen", originalName="Paths Unseen", skillId=3},
        new Skill(130){collection=1, role=Role.PATHFINDER, skillCost=3, dataName="Word of Warning", originalName="Word of Warning", skillId=4},
        new Skill(131){collection=1, role=Role.PATHFINDER, skillCost=3, dataName="Baited Trap", originalName="Baited Trap", skillId=5},
        new Skill(132){collection=1, role=Role.PATHFINDER, skillCost=3, dataName="Trail Sign", originalName="Trail Sign", skillId=6},
        new Skill(133){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="Ambush", originalName="Ambush", skillId=7},
        new Skill(134){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="Ambush", originalName="Ambush", skillId=8},
        new Skill(135){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="A Shortcut", originalName="A Shortcut", skillId=9},
        new Skill(136){collection=1, role=Role.PATHFINDER, skillCost=7, dataName="Find a Way", originalName="Find a Way", skillId=10},
        new Skill(137){collection=1, role=Role.PATHFINDER, skillCost=12, dataName="Unstoppable", originalName="Unstoppable", skillId=11},
        new Skill(138){collection=1, role=Role.PATHFINDER, skillCost=12, dataName="Honed Instinct", originalName="Honed Instinct", skillId=12},
        new Skill(139){collection=5, role=Role.PROVISIONER, skillCost=0, dataName="Foraging", originalName="Foraging", skillId=1},
        new Skill(140){collection=5, role=Role.PROVISIONER, skillCost=0, dataName="Waybread", originalName="Waybread", skillId=2},
        new Skill(141){collection=5, role=Role.PROVISIONER, skillCost=0, dataName="Waybread", originalName="Waybread", skillId=3},
        new Skill(142){collection=5, role=Role.PROVISIONER, skillCost=3, dataName="Mending", originalName="Mending", skillId=4},
        new Skill(143){collection=5, role=Role.PROVISIONER, skillCost=3, dataName="Gathering", originalName="Gathering", skillId=5},
        new Skill(144){collection=5, role=Role.PROVISIONER, skillCost=3, dataName="Good Cheer", originalName="Good Cheer", skillId=6},
        new Skill(145){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Herbs", originalName="Herbs", skillId=7},
        new Skill(146){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Respite", originalName="Respite", skillId=8},
        new Skill(147){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Pleasant Company", originalName="Pleasant Company", skillId=9},
        new Skill(148){collection=5, role=Role.PROVISIONER, skillCost=7, dataName="Heavy Packs", originalName="Heavy Packs", skillId=10},
        new Skill(149){collection=5, role=Role.PROVISIONER, skillCost=12, dataName="Feasting", originalName="Feasting", skillId=11},
        new Skill(150){collection=5, role=Role.PROVISIONER, skillCost=12, dataName="Hope Renewed", originalName="Hope Renewed", skillId=12},
        new Skill(151){collection=5, role=Role.SHIELDMAIDEN, skillCost=0, dataName="As One", originalName="As One", skillId=1},
        new Skill(152){collection=5, role=Role.SHIELDMAIDEN, skillCost=0, dataName="Call to Glory", originalName="Call to Glory", skillId=2},
        new Skill(153){collection=5, role=Role.SHIELDMAIDEN, skillCost=0, dataName="Call to Glory", originalName="Call to Glory", skillId=3},
        new Skill(154){collection=5, role=Role.SHIELDMAIDEN, skillCost=3, dataName="Taunting Cry", originalName="Taunting Cry", skillId=4},
        new Skill(155){collection=5, role=Role.SHIELDMAIDEN, skillCost=3, dataName="As One", originalName="As One", skillId=5},
        new Skill(156){collection=5, role=Role.SHIELDMAIDEN, skillCost=3, dataName="Press the Advantage", originalName="Press the Advantage", skillId=6},
        new Skill(157){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Back to Back", originalName="Back to Back", skillId=7},
        new Skill(158){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Momentum", originalName="Momentum", skillId=8},
        new Skill(159){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Force Them Back", originalName="Force Them Back", skillId=9},
        new Skill(160){collection=5, role=Role.SHIELDMAIDEN, skillCost=7, dataName="Flanking Strike", originalName="Flanking Strike", skillId=10},
        new Skill(161){collection=5, role=Role.SHIELDMAIDEN, skillCost=12, dataName="Overrun", originalName="Overrun", skillId=11},
        new Skill(162){collection=5, role=Role.SHIELDMAIDEN, skillCost=12, dataName="Carry the Day", originalName="Carry the Day", skillId=12},
        new Skill(163){collection=3, role=Role.SMITH, skillCost=0, dataName="Reforging", originalName="Reforging", skillId=1},
        new Skill(164){collection=3, role=Role.SMITH, skillCost=0, dataName="Thrice-Forged Steel", originalName="Thrice-Forged Steel", skillId=2},
        new Skill(165){collection=3, role=Role.SMITH, skillCost=0, dataName="Thrice-Forged Steel", originalName="Thrice-Forged Steel", skillId=3},
        new Skill(166){collection=3, role=Role.SMITH, skillCost=3, dataName="Unbowed", originalName="Unbowed", skillId=4},
        new Skill(167){collection=3, role=Role.SMITH, skillCost=3, dataName="Industrious", originalName="Industrious", skillId=5},
        new Skill(168){collection=3, role=Role.SMITH, skillCost=3, dataName="Industrious", originalName="Industrious", skillId=6},
        new Skill(169){collection=3, role=Role.SMITH, skillCost=7, dataName="Strike the Anvil", originalName="Strike the Anvil", skillId=7},
        new Skill(170){collection=3, role=Role.SMITH, skillCost=7, dataName="Dwarf-Linked Rings", originalName="Dwarf-Linked Rings", skillId=8},
        new Skill(171){collection=3, role=Role.SMITH, skillCost=7, dataName="Elf-Wrights' Grace", originalName="Elf-Wrights' Grace", skillId=9},
        new Skill(172){collection=3, role=Role.SMITH, skillCost=7, dataName="Craft of Men", originalName="Craft of Men", skillId=10},
        new Skill(173){collection=3, role=Role.SMITH, skillCost=12, dataName="[Cuneiform] Inscription", originalName="Cirith Inscription", skillId=11},
        new Skill(174){collection=3, role=Role.SMITH, skillCost=12, dataName="Forge's Fire", originalName="Forge's Fire", skillId=12},
        new Skill(175){collection=5, role=Role.SOLDIER, skillCost=0, dataName="Comrade in Arms", originalName="Comrade in Arms", skillId=1},
        new Skill(176){collection=5, role=Role.SOLDIER, skillCost=0, dataName="Love of War and Valour", originalName="Love of War and Valour", skillId=2},
        new Skill(177){collection=5, role=Role.SOLDIER, skillCost=0, dataName="Love of War and Valour", originalName="Love of War and Valour", skillId=3},
        new Skill(178){collection=5, role=Role.SOLDIER, skillCost=3, dataName="Fighting Advance", originalName="Fighting Advance", skillId=4},
        new Skill(179){collection=5, role=Role.SOLDIER, skillCost=3, dataName="Fighting Advance", originalName="Fighting Advance", skillId=5},
        new Skill(180){collection=5, role=Role.SOLDIER, skillCost=3, dataName="Fighting Advance", originalName="Fighting Advance", skillId=6},
        new Skill(181){collection=5, role=Role.SOLDIER, skillCost=7, dataName="On Your Orders", originalName="On Your Orders", skillId=7},
        new Skill(182){collection=5, role=Role.SOLDIER, skillCost=7, dataName="On Your Orders", originalName="On Your Orders", skillId=8},
        new Skill(183){collection=5, role=Role.SOLDIER, skillCost=7, dataName="Sleep Anywhere", originalName="Sleep Anywhere", skillId=9},
        new Skill(184){collection=5, role=Role.SOLDIER, skillCost=7, dataName="Sleep Anywhere", originalName="Sleep Anywhere", skillId=10},
        new Skill(185){collection=5, role=Role.SOLDIER, skillCost=12, dataName="Break the Wave", originalName="Break the Wave", skillId=11},
        new Skill(186){collection=5, role=Role.SOLDIER, skillCost=12, dataName="Break the Wave", originalName="Break the Wave", skillId=12},
        new Skill(187){collection=3, role=Role.TRAVELLER, skillCost=0, dataName="Over Ridge and Rill", originalName="Over Ridge and Rill", skillId=1},
        new Skill(188){collection=3, role=Role.TRAVELLER, skillCost=0, dataName="Many Paths to Tread", originalName="Many Paths to Tread", skillId=2},
        new Skill(189){collection=3, role=Role.TRAVELLER, skillCost=0, dataName="Many Paths to Tread", originalName="Many Paths to Tread", skillId=3},
        new Skill(190){collection=3, role=Role.TRAVELLER, skillCost=3, dataName="Camaraderie", originalName="Camaraderie", skillId=4},
        new Skill(191){collection=3, role=Role.TRAVELLER, skillCost=3, dataName="Around Every Corner", originalName="Around Every Corner", skillId=5},
        new Skill(192){collection=3, role=Role.TRAVELLER, skillCost=3, dataName="Seasoned", originalName="Seasoned", skillId=6},
        new Skill(193){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Fleet of Foot", originalName="Fleet of Foot", skillId=7},
        new Skill(194){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Nothing to Fear", originalName="Nothing to Fear", skillId=8},
        new Skill(195){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Campfire Tales", originalName="Campfire Tales", skillId=9},
        new Skill(196){collection=3, role=Role.TRAVELLER, skillCost=7, dataName="Paths Less Travelled", originalName="Paths Less Travelled", skillId=10},
        new Skill(197){collection=3, role=Role.TRAVELLER, skillCost=12, dataName="Wanderlust", originalName="Wanderlust", skillId=11},
        new Skill(198){collection=3, role=Role.TRAVELLER, skillCost=12, dataName="Forgotten Roads", originalName="Forgotten Roads", skillId=12},
        new Skill(199){collection=5, role=Role.TRICKSTER, skillCost=0, dataName="Merry Chase", originalName="Merry Chase", skillId=1},
        new Skill(200){collection=5, role=Role.TRICKSTER, skillCost=0, dataName="Chicanery", originalName="Chicanery", skillId=2},
        new Skill(201){collection=5, role=Role.TRICKSTER, skillCost=0, dataName="Chicanery", originalName="Chicanery", skillId=3},
        new Skill(202){collection=5, role=Role.TRICKSTER, skillCost=3, dataName="Clever Distraction", originalName="Clever Distraction", skillId=4},
        new Skill(203){collection=5, role=Role.TRICKSTER, skillCost=3, dataName="Improvisation", originalName="Improvisation", skillId=5},
        new Skill(204){collection=5, role=Role.TRICKSTER, skillCost=3, dataName="Trick up Your Sleeve", originalName="Trick up Your Sleeve", skillId=6},
        new Skill(205){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Cutting Remark", originalName="Cutting Remark", skillId=7},
        new Skill(206){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Gallows Humor", originalName="Gallows Humor", skillId=8},
        new Skill(207){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Look over There!", originalName="Look over There!", skillId=9},
        new Skill(208){collection=5, role=Role.TRICKSTER, skillCost=7, dataName="Confusticate", originalName="Confusticate", skillId=10},
        new Skill(209){collection=5, role=Role.TRICKSTER, skillCost=12, dataName="Eye for Opportunity", originalName="Eye for Opportunity", skillId=11},
        new Skill(210){collection=5, role=Role.TRICKSTER, skillCost=12, dataName="Quite a Spectacle", originalName="Quite a Spectacle", skillId=12}
    };
}
